services:
  myrargb:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - CHROME_URL=http://browser:4444
      - LOGGER_LEVEL=ERROR
    command: /app/.venv/bin/python /app/app.py
      

  browser:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    shm_size: "2g"
      
